name: Code Purity
on:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
       fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Execute the command
      run: npm run lint
  typecheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
       fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Execute the command
      run: npm run typecheck
